ALTER TABLE
    "users"
ADD
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE
    "states"
ADD
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE
    "cities"
ADD
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE
    "addresses"
ADD
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE
    "carts"
ADD
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE
    "favorites"
ADD
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE
    "products"
ADD
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE
    "roles"
ADD
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE
    "sales"
ADD
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE
    "shopping"
ADD
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

